version: "3.9"

services:
  n8n:
    # En lugar de 'image', ahora usamos 'build' para construir la imagen
    # a partir de nuestro Dockerfile local.
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n-custom  # Opcional: le damos un nombre a la imagen que se creará.
    container_name: N8N
    ports:
      - "5678:5678"
    volumes:
      - ./.n8n:/home/node/.n8n
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - gotenberg

  gotenberg:
    image: gotenberg/gotenberg:latest
    container_name: gotenberg
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
