
services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n-custom
    container_name: N8N
    env_file:
      - .env
    ports:
      - "5678:5678"
    volumes:
      - ./.n8n:/home/node/.n8n
    restart: unless-stopped
    networks:
      - app-network

  gotenberg:
    image: gotenberg/gotenberg:latest
    container_name: gotenberg
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - PORT=3001
      - N8N_USER_SETTINGS_ENV_VARS=["N8N_SECRETARY_EMAIL", "N8N_RECTOR_EMAIL"]


  pdf_reader:
    build:
      context: ./pdf_reader
      dockerfile: Dockerfile
    container_name: pdf_reader
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app-network

  # reranker:
  #   build:
  #     context: ./reranker
  #     dockerfile: Dockerfile
  #   container_name: reranker
  #   ports:
  #     - "8000:8000"
  #   restart: unless-stopped
  #   networks:
  #     - app-network

  # whereas_selector:
  #   build:
  #     context: ./whereas_selector
  #     dockerfile: Dockerfile
  #   container_name: whereas_selector
  #   ports:
  #     - "3002:3002"
  #   restart: unless-stopped
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge